import {
  LayoutDashboard,
  GraduationCap,
  Users,
  UserRound,
  Contact,
  CalendarClock,
  ClipboardList,
  BookOpen,
  Video,
  FolderOpen,
  Settings,
  ShieldCheck,
  FileQuestion,
  AlertTriangle,
  Wallet,
  Sliders,
  UserPlus,
  Megaphone,
  Zap,
  MessageCircle,
  MessageSquareText,
  BarChart3,
  Activity,
  LifeBuoy,
  Trophy,
  Award,
  Sparkles,
  Share2,
  Library,
  Bot,
  NotebookPen,
  Wand2,
  ShieldAlert,
  Route,
  AlarmClock,
  LayoutGrid,
  HeartPulse,
  Cpu,
  KeyRound,
  CreditCard,
  Plug,
  Mail,
  type LucideIcon,
} from "lucide-react";
import type { IconKey } from "@/lib/nav-config";

export const ICON_MAP: Record<IconKey, LucideIcon> = {
  dashboard: LayoutDashboard,
  students: GraduationCap,
  parents: Contact,
  teachers: UserRound,
  academics: BookOpen,
  batches: Users,
  timetable: CalendarClock,
  material: FolderOpen,
  settingsUsers: Settings,
  settingsRoles: ShieldCheck,
  homework: ClipboardList,
  recordings: Video,
  attendance: BookOpen,
  tests: FileQuestion,
  atRisk: AlertTriangle,
  payments: Wallet,
  performance: Sliders,
  leads: UserPlus,
  announcements: Megaphone,
  automation: Zap,
  communication: MessageCircle,
  messageTemplates: MessageSquareText,
  analytics: BarChart3,
  engagement: Activity,
  interventions: LifeBuoy,
  leaderboard: Trophy,
  badges: Award,
  gamification: Sparkles,
  referrals: Share2,
  support: LifeBuoy,
  knowledgeBase: Library,
  studyAssistant: Bot,
  studyPlan: NotebookPen,
  teacherAssistant: Wand2,
  predictiveRisk: ShieldAlert,
  learningPath: Route,
  examPrep: AlarmClock,
  commandCenter: LayoutGrid,
  systemHealth: HeartPulse,
  aiUsage: Cpu,
  apiKeys: KeyRound,
  paymentGateway: CreditCard,
  integrations: Plug,
  notesSubscription: Mail,
};
